package ai.agentscentral.anthropic.client.common;

/**
 * Conversation role as defined by the Anthropic Messages API.
 *
 * <p>Every message in a request or response carries one of these roles, determining
 * how the model interprets the content.</p>
 *
 * @author Rizwan Idrees
 */
public enum Role {
    /** A message sent by the end user or the framework on behalf of the user. */
    user,
    /** A message generated by the Claude model. */
    assistant
}
