package ai.agentscentral.openai.client.response.parameters;

/**
 * A single tool-call instruction returned by the model within a {@link ChoiceMessage}.
 *
 * @param id       unique tool-call identifier generated by the model; echoed back in the
 *                 subsequent {@code tool} message
 * @param type     always {@code "function"} in current API versions
 * @param function the function name and its JSON-encoded arguments
 *
 * @author Rizwan Idrees
 */
public record ToolCall(String id, String type, Function function) {
}
