package ai.agentscentral.anthropic.client.response.attributes;

/**
 * {@link ResponseContent} implementation for plain-text output blocks
 * ({@link ResponseContentType#text}).
 *
 * @param type the content-block type; always {@link ResponseContentType#text}
 * @param text the text generated by the model
 *
 * @author Rizwan Idrees
 */
public record TextResponseContent(ResponseContentType type, String text) implements ResponseContent {
}
